type ParameterValueType = "string" | "integer" | "number" | "boolean" | "enum";

export type AssemblyParameterDefinitionSeed = {
  key: string;
  label: string;
  valueType: ParameterValueType;
  required?: boolean;
  defaultValue?: string | number | boolean;
  enumOptions?: string[];
  unit?: string;
  helpText?: string;
  estimatorFacing?: boolean;
  sortOrder?: number;
  minValue?: number;
  maxValue?: number;
};

export type AssemblyVariantSeed = {
  variantKey: string;
  variantValue?: string;
  notes?: string;
};

const BREAKER_SIZE_OPTIONS = [
  "15", "20", "25", "30", "35", "40", "45", "50", "60", "70", "80", "90", "100", "110", "125", "150",
  "175", "200", "225", "250", "300", "350", "400",
];

const BREAKER_FAMILY_OPTIONS = ["standard", "gfci", "afci", "tandem", "dual_function_gfci_afci"];

const BRANCH_COMMON: AssemblyParameterDefinitionSeed[] = [
  {
    key: "run_length",
    label: "Run Length",
    valueType: "number",
    required: true,
    unit: "ft",
    minValue: 5,
    maxValue: 500,
    helpText: "Estimated circuit route length from source to destination.",
  },
  {
    key: "raceway_type",
    label: "Raceway / Cable Type",
    valueType: "enum",
    required: true,
    enumOptions: ["nm", "emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ser", "ac_mc"],
    defaultValue: "nm",
  },
  {
    key: "route_access",
    label: "Route Access",
    valueType: "enum",
    required: true,
    enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
    defaultValue: "finished_wall",
  },
  {
    key: "conductor_type",
    label: "Conductor Type",
    valueType: "enum",
    required: true,
    enumOptions: ["copper", "aluminum"],
    defaultValue: "copper",
  },
  {
    key: "breaker_size",
    label: "Breaker Size",
    valueType: "enum",
    required: true,
    enumOptions: BREAKER_SIZE_OPTIONS,
    defaultValue: "20",
    helpText: "Standard breaker-size dropdown used across branch workflows.",
  },
  {
    key: "breaker_family",
    label: "Breaker Type",
    valueType: "enum",
    required: true,
    enumOptions: BREAKER_FAMILY_OPTIONS,
    defaultValue: "standard",
  },
];

export const PHASE_1_PARAMETER_DEFINITIONS: Record<number, AssemblyParameterDefinitionSeed[]> = {
  6: [
    {
      key: "run_length",
      label: "Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 150,
    },
    {
      key: "wall_type",
      label: "Wall Type",
      valueType: "enum",
      required: true,
      enumOptions: ["open_framing", "finished_wall", "exterior"],
      defaultValue: "finished_wall",
    },
    {
      key: "location_type",
      label: "Location",
      valueType: "enum",
      required: true,
      enumOptions: ["interior", "garage", "exterior", "kitchen", "bathroom", "laundry"],
      defaultValue: "interior",
    },
    {
      key: "device_rating",
      label: "Device Rating",
      valueType: "enum",
      required: true,
      enumOptions: ["15a", "20a"],
      defaultValue: "15a",
      helpText: "Choose 20A where required by the served circuit/location.",
    },
    {
      key: "device_15a_qty",
      label: "15A Device Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "device_20a_qty",
      label: "20A Device Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_14_2",
      label: "14/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_12_2",
      label: "12/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
  ],
  7: [
    {
      key: "run_length",
      label: "Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 150,
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "patch_scope",
      label: "Patch Scope",
      valueType: "enum",
      required: false,
      enumOptions: ["none", "minor", "major"],
      defaultValue: "minor",
    },
    {
      key: "device_rating",
      label: "Device Rating",
      valueType: "enum",
      required: true,
      enumOptions: ["15a", "20a"],
      defaultValue: "15a",
      helpText: "Select the receptacle rating for the relocated point.",
    },
    {
      key: "device_15a_qty",
      label: "15A Device Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "device_20a_qty",
      label: "20A Device Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_14_2",
      label: "14/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_12_2",
      label: "12/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
  ],
  11: [
    {
      key: "wall_type",
      label: "Wall Type",
      valueType: "enum",
      required: true,
      enumOptions: ["open_framing", "finished_wall", "exterior"],
      defaultValue: "finished_wall",
    },
    {
      key: "switch_type",
      label: "Switch Type",
      valueType: "enum",
      required: true,
      enumOptions: ["single_pole", "three_way", "dimmer", "smart"],
      defaultValue: "single_pole",
    },
    {
      key: "neutral_present",
      label: "Neutral Present",
      valueType: "boolean",
      defaultValue: true,
    },
  ],
  13: [
    {
      key: "ceiling_type",
      label: "Ceiling Type",
      valueType: "enum",
      required: true,
      enumOptions: ["flat", "vaulted", "sloped"],
      defaultValue: "flat",
    },
    {
      key: "attic_access",
      label: "Attic Access",
      valueType: "enum",
      required: true,
      enumOptions: ["accessible", "limited", "none"],
      defaultValue: "accessible",
    },
    {
      key: "mounting_height",
      label: "Mounting Height",
      valueType: "number",
      unit: "ft",
      minValue: 7,
      maxValue: 15,
      defaultValue: 8,
    },
  ],
  14: [
    {
      key: "attic_access",
      label: "Attic Access",
      valueType: "enum",
      required: true,
      enumOptions: ["accessible", "limited", "none"],
      defaultValue: "limited",
    },
    {
      key: "fixture_type",
      label: "Fixture Type",
      valueType: "enum",
      required: true,
      enumOptions: ["wafer", "can"],
      defaultValue: "wafer",
    },
    {
      key: "ceiling_type",
      label: "Ceiling Type",
      valueType: "enum",
      required: true,
      enumOptions: ["flat", "vaulted", "sloped"],
      defaultValue: "flat",
    },
  ],
  17: [
    ...BRANCH_COMMON,
    {
      key: "ampacity",
      label: "Circuit Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 15,
      maxValue: 60,
      defaultValue: 20,
    },
    {
      key: "breaker_pole_config",
      label: "Breaker Pole Configuration",
      valueType: "enum",
      required: true,
      enumOptions: ["1_pole", "2_pole"],
      defaultValue: "1_pole",
    },
    {
      key: "conductor_size",
      label: "Conductor Size",
      valueType: "enum",
      required: true,
      enumOptions: ["14_awg", "12_awg", "10_awg", "8_awg", "6_awg"],
      defaultValue: "12_awg",
    },
  ],
  18: [
    ...BRANCH_COMMON,
    {
      key: "endpoint_device",
      label: "Endpoint Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nema_14_50", "nema_6_50", "hardwired"],
      defaultValue: "nema_14_50",
      helpText: "14-50 is 4-prong; 6-50 is 3-prong; hardwired omits receptacle hardware.",
    },
    {
      key: "ampacity",
      label: "Circuit Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 20,
      maxValue: 125,
      defaultValue: 50,
    },
    {
      key: "breaker_pole_config",
      label: "Breaker Pole Configuration",
      valueType: "enum",
      required: true,
      enumOptions: ["2_pole"],
      defaultValue: "2_pole",
    },
    {
      key: "conductor_size",
      label: "Conductor Size",
      valueType: "enum",
      required: true,
      enumOptions: ["10_awg", "8_awg", "6_awg", "4_awg", "2_awg"],
      defaultValue: "6_awg",
    },
    {
      key: "endpoint_14_50_qty",
      label: "14-50 Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "endpoint_6_50_qty",
      label: "6-50 Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "endpoint_hardwire_qty",
      label: "Hardwired Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_6_3",
      label: "6/3 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_6_2",
      label: "6/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
  ],
  // Wave 4: Feeder Assemblies
  19: [
    ...BRANCH_COMMON,
    {
      key: "ampacity",
      label: "Circuit Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 15,
      maxValue: 30,
      defaultValue: 20,
    },
    {
      key: "breaker_pole_config",
      label: "Breaker Configuration",
      valueType: "enum",
      required: true,
      enumOptions: ["2_pole_common_trip", "2_pole_common_handle"],
      defaultValue: "2_pole_common_trip",
    },
    {
      key: "conductor_size",
      label: "Conductor Size",
      valueType: "enum",
      required: true,
      enumOptions: ["14_awg", "12_awg", "10_awg"],
      defaultValue: "12_awg",
    },
  ],
  20: [
    ...BRANCH_COMMON,
    {
      key: "ampacity",
      label: "Feeder Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 200,
      defaultValue: 100,
    },
    {
      key: "conductor_size",
      label: "Conductor Size",
      valueType: "enum",
      required: true,
      enumOptions: ["4_awg", "2_awg", "1_awg", "1_0_awg", "2_0_awg", "3_0_awg"],
      defaultValue: "2_0_awg",
    },
    {
      key: "voltage_drop_review_required",
      label: "Voltage Drop Review Required",
      valueType: "boolean",
      required: false,
      defaultValue: false,
    },
  ],
  21: [
    ...BRANCH_COMMON,
    {
      key: "ampacity",
      label: "Feeder Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 200,
      defaultValue: 100,
    },
    {
      key: "conductor_size",
      label: "Conductor Size",
      valueType: "enum",
      required: true,
      enumOptions: ["4_awg", "2_awg", "1_awg", "1_0_awg", "2_0_awg", "3_0_awg"],
      defaultValue: "2_0_awg",
    },
    {
      key: "overhead_or_underground",
      label: "Routing Method",
      valueType: "enum",
      required: true,
      enumOptions: ["overhead", "underground"],
      defaultValue: "underground",
    },
    {
      key: "voltage_drop_review_required",
      label: "Voltage Drop Review Required",
      valueType: "boolean",
      required: false,
      defaultValue: false,
    },
  ],
  22: [
    {
      key: "panel_make",
      label: "Panel Manufacturer",
      valueType: "enum",
      required: true,
      enumOptions: ["eaton", "siemens", "square_d", "ge", "other"],
    },
    {
      key: "breaker_pole_config",
      label: "Breaker Pole Configuration",
      valueType: "enum",
      required: true,
      enumOptions: ["1_pole", "2_pole"],
      defaultValue: "1_pole",
    },
    {
      key: "breaker_family",
      label: "Breaker Family",
      valueType: "enum",
      required: false,
      enumOptions: ["standard", "afci", "gfci", "dual_function"],
      defaultValue: "standard",
    },
  ],
  23: [
    {
      key: "panel_make",
      label: "Panel Manufacturer",
      valueType: "enum",
      required: true,
      enumOptions: ["eaton", "siemens", "square_d", "ge", "other"],
    },
    {
      key: "breaker_pole_config",
      label: "Breaker Pole Configuration",
      valueType: "enum",
      required: true,
      enumOptions: ["1_pole", "2_pole"],
      defaultValue: "1_pole",
    },
  ],
  24: [
    {
      key: "panel_make",
      label: "Panel Manufacturer",
      valueType: "enum",
      required: true,
      enumOptions: ["eaton", "siemens", "square_d", "ge", "other"],
    },
    {
      key: "breaker_family",
      label: "Protection Type",
      valueType: "enum",
      required: true,
      enumOptions: ["afci", "gfci", "dual_function"],
      defaultValue: "afci",
    },
  ],
  27: [
    {
      key: "panel_amp_rating",
      label: "Panel Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 100,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "panel_location_type",
      label: "Panel Location",
      valueType: "enum",
      required: true,
      enumOptions: ["interior", "garage", "exterior"],
      defaultValue: "interior",
    },
    {
      key: "overhead_or_underground",
      label: "Service Type",
      valueType: "enum",
      required: true,
      enumOptions: ["overhead", "underground"],
      defaultValue: "overhead",
    },
  ],
  28: [
    {
      key: "service_ampacity",
      label: "Service Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 100,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "overhead_or_underground",
      label: "Service Type",
      valueType: "enum",
      required: true,
      enumOptions: ["overhead", "underground"],
      defaultValue: "overhead",
    },
    {
      key: "conductor_type",
      label: "Conductor Type",
      valueType: "enum",
      required: true,
      enumOptions: ["copper", "aluminum"],
      defaultValue: "aluminum",
    },
  ],
  29: [
    {
      key: "meter_base_amp_rating",
      label: "Meter Base Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 100,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "utility_coordination_required",
      label: "Utility Coordination Required",
      valueType: "boolean",
      defaultValue: true,
    },
  ],
  30: [
    {
      key: "interior_or_exterior_disconnect",
      label: "Disconnect Location",
      valueType: "enum",
      required: true,
      enumOptions: ["interior", "exterior"],
      defaultValue: "exterior",
    },
    {
      key: "service_ampacity",
      label: "Service Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 100,
      maxValue: 400,
      defaultValue: 200,
    },
  ],
  32: [
    {
      key: "service_ampacity",
      label: "Service Ampacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 100,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "gec_upgrade_qty",
      label: "Grounding Electrode Conductor Upgrades",
      valueType: "integer",
      minValue: 0,
      maxValue: 1,
      defaultValue: 0,
      helpText: "Optional #35 child quantity.",
    },
    {
      key: "bonding_correction_qty",
      label: "Bonding Corrections",
      valueType: "integer",
      minValue: 0,
      maxValue: 1,
      defaultValue: 0,
      helpText: "Optional #36 child quantity.",
    },
    {
      key: "surge_protection_qty",
      label: "Whole-Home Surge Devices",
      valueType: "integer",
      minValue: 0,
      maxValue: 1,
      defaultValue: 0,
      helpText: "Optional #37 child quantity.",
    },
    {
      key: "permit_allowance_qty",
      label: "Permit Allowance Quantity",
      valueType: "integer",
      minValue: 0,
      maxValue: 1,
      defaultValue: 1,
      helpText: "Optional #72 child quantity.",
    },
  ],
  43: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
      helpText: "Estimated cable route from panel to water heater.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "30",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
    },
    {
      key: "endpoint_device",
      label: "Endpoint Type",
      valueType: "enum",
      required: true,
      enumOptions: ["hardwired", "nema_14_30"],
      defaultValue: "hardwired",
      helpText: "Water heaters are typically hardwired; use 14-30 only when specified.",
    },
    {
      key: "endpoint_14_30_qty",
      label: "14-30 Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "endpoint_hardwire_qty",
      label: "Hardwired Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_10_3",
      label: "10/3 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_10_2",
      label: "10/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
  ],
  44: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
      helpText: "Estimated cable route from panel to range.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "50",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
      helpText: "Offer GFCI as an optional premium safety upgrade.",
    },
    {
      key: "endpoint_device",
      label: "Endpoint Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nema_14_50", "hardwired"],
      defaultValue: "nema_14_50",
      helpText: "Use 14-50 for range and oven receptacle installs; choose hardwired when applicable.",
    },
    {
      key: "endpoint_14_50_qty",
      label: "14-50 Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "endpoint_hardwire_qty",
      label: "Hardwired Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_6_3",
      label: "6/3 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_6_2",
      label: "6/2 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
  ],
  45: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
      helpText: "Estimated cable route from panel to dryer.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "30",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
      helpText: "Offer GFCI as an optional premium safety upgrade.",
    },
    {
      key: "endpoint_device",
      label: "Endpoint Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nema_14_30", "nema_14_50"],
      defaultValue: "nema_14_30",
      helpText: "Dryer installs are plug-and-cord only in this workflow.",
    },
    {
      key: "endpoint_14_30_qty",
      label: "14-30 Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "endpoint_14_50_qty",
      label: "14-50 Endpoint Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_10_3",
      label: "10/3 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
    {
      key: "run_length_6_3",
      label: "6/3 Run Length",
      valueType: "number",
      required: false,
      defaultValue: 0,
      estimatorFacing: false,
    },
  ],
  48: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
      helpText: "Estimated route from panel to condenser disconnect location.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "raceway_type",
      label: "Raceway / Cable Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nm", "emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ser", "ac_mc"],
      defaultValue: "emt",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "30",
      helpText: "Typical residential condenser values are 25A/30A, with 40A/50A also common.",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
      helpText: "GFCI can be offered as an optional safety upgrade.",
    },
  ],
  49: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
      helpText: "Estimated route from panel to air handler/furnace electrical connection.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "raceway_type",
      label: "Raceway / Cable Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nm", "emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ser", "ac_mc"],
      defaultValue: "nm",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "30",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
      helpText: "GFCI can be offered as an optional safety upgrade.",
    },
  ],
  59: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "raceway_type",
      label: "Raceway / Cable Type",
      valueType: "enum",
      required: true,
      enumOptions: ["emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ac_mc", "nm", "ser"],
      defaultValue: "emt",
    },
    {
      key: "ev_connection_method",
      label: "EV Connection Method",
      valueType: "enum",
      required: true,
      enumOptions: ["cord_and_plug", "hardwired"],
      defaultValue: "hardwired",
      helpText: "Cord-and-plug EV installations require GFCI breaker protection.",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "50",
      helpText: "Typical EV sizes are 40A, 50A, and 60A.",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
    },
  ],
  60: [
    {
      key: "run_length",
      label: "Circuit Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "raceway_type",
      label: "Raceway / Cable Type",
      valueType: "enum",
      required: true,
      enumOptions: ["emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ac_mc", "nm", "ser"],
      defaultValue: "emt",
    },
    {
      key: "ev_connection_method",
      label: "EV Connection Method",
      valueType: "enum",
      required: true,
      enumOptions: ["cord_and_plug", "hardwired"],
      defaultValue: "hardwired",
      helpText: "Cord-and-plug EV installations require GFCI breaker protection.",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_SIZE_OPTIONS,
      defaultValue: "50",
      helpText: "Typical EV sizes are 40A, 50A, and 60A.",
    },
    {
      key: "breaker_family",
      label: "Breaker Type",
      valueType: "enum",
      required: true,
      enumOptions: BREAKER_FAMILY_OPTIONS,
      defaultValue: "standard",
    },
    {
      key: "customer_supplied_credit",
      label: "Customer-Supplied Charger Credit",
      valueType: "number",
      required: false,
      unit: "USD",
      minValue: 0,
      maxValue: 5000,
      defaultValue: 0,
      helpText: "Optional credit based on customer charger receipt.",
    },
  ],
  63: [
    {
      key: "run_length",
      label: "Feeder Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 500,
      helpText: "Estimated route from panel to spa disconnect location.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "feeder_ampacity",
      label: "Feeder Ampacity",
      valueType: "enum",
      required: true,
      enumOptions: ["50a", "60a"],
      defaultValue: "50a",
    },
    {
      key: "disconnect_type",
      label: "Disconnect Type",
      valueType: "enum",
      required: true,
      enumOptions: ["gfci_spa_panel", "non_gfci_disconnect"],
      defaultValue: "gfci_spa_panel",
    },
    {
      key: "bonding_required",
      label: "Include Bonding",
      valueType: "boolean",
      required: false,
      defaultValue: true,
    },
  ],
  64: [
    {
      key: "run_length",
      label: "Feeder Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 500,
      helpText: "Estimated route from panel to pool equipment disconnect.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "feeder_ampacity",
      label: "Feeder Ampacity",
      valueType: "enum",
      required: true,
      enumOptions: ["50a", "60a"],
      defaultValue: "60a",
    },
    {
      key: "equipment_profile",
      label: "Equipment Profile",
      valueType: "enum",
      required: true,
      enumOptions: ["single_pump", "multi_equipment_pad"],
      defaultValue: "single_pump",
    },
    {
      key: "bonding_required",
      label: "Include Bonding",
      valueType: "boolean",
      required: false,
      defaultValue: true,
    },
  ],
  65: [
    {
      key: "run_length",
      label: "Feeder Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 500,
      helpText: "Estimated route from panel to spa/hot tub disconnect location.",
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
    {
      key: "feeder_ampacity",
      label: "Feeder Ampacity",
      valueType: "enum",
      required: true,
      enumOptions: ["50a", "60a"],
      defaultValue: "50a",
    },
    {
      key: "location_type",
      label: "Location Type",
      valueType: "enum",
      required: true,
      enumOptions: ["exterior", "deck", "pool_spa_pad"],
      defaultValue: "exterior",
    },
    {
      key: "bonding_required",
      label: "Include Bonding",
      valueType: "boolean",
      required: false,
      defaultValue: true,
    },
  ],
  75: [
    {
      key: "ceiling_type",
      label: "Ceiling Type",
      valueType: "enum",
      required: true,
      enumOptions: ["flat", "vaulted", "sloped"],
      defaultValue: "flat",
    },
    {
      key: "support_box_scope",
      label: "Support Box Scope",
      valueType: "enum",
      required: true,
      enumOptions: ["existing", "upgrade_required", "new_box"],
      defaultValue: "upgrade_required",
    },
  ],
  77: [
    {
      key: "device_type",
      label: "Detector Type",
      valueType: "enum",
      required: true,
      enumOptions: ["smoke", "co", "combo"],
      defaultValue: "combo",
    },
  ],
  78: [
    {
      key: "run_length",
      label: "Interconnect Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 200,
    },
    {
      key: "interconnect_type",
      label: "Interconnect Type",
      valueType: "enum",
      required: true,
      enumOptions: ["hardwired", "wireless"],
      defaultValue: "hardwired",
    },
    {
      key: "attic_access",
      label: "Attic Access",
      valueType: "enum",
      required: true,
      enumOptions: ["accessible", "limited", "none"],
      defaultValue: "limited",
    },
  ],
  79: [
    {
      key: "replace_detector_qty",
      label: "Replace Detector Quantity",
      valueType: "integer",
      minValue: 0,
      maxValue: 20,
      defaultValue: 0,
    },
    {
      key: "new_detector_qty",
      label: "New Hardwired Detector Quantity",
      valueType: "integer",
      minValue: 0,
      maxValue: 10,
      defaultValue: 0,
    },
    {
      key: "access_difficulty_qty",
      label: "Access Difficulty Add-On Quantity",
      valueType: "integer",
      minValue: 0,
      maxValue: 10,
      defaultValue: 0,
    },
  ],
  80: [
    {
      key: "ducting_scope",
      label: "Ducting Scope",
      valueType: "enum",
      required: true,
      enumOptions: ["existing", "new", "reroute"],
      defaultValue: "existing",
    },
    {
      key: "attic_access",
      label: "Attic Access",
      valueType: "enum",
      required: true,
      enumOptions: ["accessible", "limited", "none"],
      defaultValue: "limited",
    },
  ],
  83: [
    {
      key: "trench_length",
      label: "Trench Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 1000,
    },
    {
      key: "surface_type",
      label: "Surface Type",
      valueType: "enum",
      required: true,
      enumOptions: ["lawn", "concrete", "asphalt", "rocky"],
      defaultValue: "lawn",
    },
    {
      key: "depth_class",
      label: "Burial Depth Class",
      valueType: "enum",
      required: true,
      enumOptions: ["12_in", "18_in", "24_in", "36_in"],
      defaultValue: "18_in",
    },
    {
      key: "boring_required",
      label: "Directional Boring Required",
      valueType: "boolean",
      defaultValue: false,
    },
  ],
  89: [
    {
      key: "panel_amp_rating",
      label: "Subpanel Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 225,
      defaultValue: 100,
    },
    {
      key: "feeder_run_length",
      label: "Feeder Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
  ],
  38: [
    {
      key: "feeder_run_length",
      label: "Feeder Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 300,
      defaultValue: 50,
    },
    {
      key: "feeder_size",
      label: "Feeder Cable Size",
      valueType: "enum",
      required: true,
      enumOptions: ["2/0", "2", "1", "1/0", "3/0", "4/0"],
      defaultValue: "2",
    },
    {
      key: "panel_amp_rating",
      label: "Subpanel Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 100,
      defaultValue: 100,
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace"],
      defaultValue: "finished_wall",
    },
  ],
  40: [
    {
      key: "run_length",
      label: "Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 300,
      defaultValue: 50,
    },
    {
      key: "equipment_type",
      label: "Equipment Type",
      valueType: "enum",
      required: true,
      enumOptions: ["pool", "spa", "hot_tub", "other"],
      defaultValue: "pool",
    },
    {
      key: "breaker_size",
      label: "Breaker Size",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 15,
      maxValue: 100,
      defaultValue: 50,
    },
  ],
  41: [
    {
      key: "feeder_run_length",
      label: "Feeder Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 300,
      defaultValue: 50,
    },
    {
      key: "route_access",
      label: "Route Access",
      valueType: "enum",
      required: true,
      enumOptions: ["open", "attic_accessible", "finished_wall", "crawlspace", "exterior_overhead"],
      defaultValue: "open",
    },
  ],
  42: [
    {
      key: "run_length",
      label: "Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 150,
      defaultValue: 30,
    },
    {
      key: "device_type",
      label: "Device Type",
      valueType: "enum",
      required: true,
      enumOptions: ["gate_opener", "exterior_control", "flood_light"],
      defaultValue: "gate_opener",
    },
  ],
  84: [
    {
      key: "transformer_rating",
      label: "Transformer Rating",
      valueType: "integer",
      required: true,
      unit: "VA",
      minValue: 10,
      maxValue: 40,
      defaultValue: 24,
    },
    {
      key: "chime_type",
      label: "Chime Type",
      valueType: "enum",
      required: false,
      enumOptions: ["wireless", "hardwired_1button", "hardwired_2button"],
      defaultValue: "hardwired_1button",
    },
  ],
  90: [
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 100,
      defaultValue: 20,
    },
    {
      key: "box_type",
      label: "Box Type",
      valueType: "enum",
      required: true,
      enumOptions: ["new_work", "old_work"],
      defaultValue: "new_work",
    },
    {
      key: "gang_count",
      label: "Gang Count",
      valueType: "integer",
      required: false,
      minValue: 1,
      maxValue: 4,
      defaultValue: 1,
    },
    {
      key: "device_grade",
      label: "Device Grade",
      valueType: "enum",
      required: false,
      enumOptions: ["standard", "commercial", "hospital"],
      defaultValue: "standard",
    },
    {
      key: "device_type",
      label: "Receptacle Type",
      valueType: "enum",
      required: false,
      enumOptions: ["15a_125v", "20a_125v", "gfci", "afci"],
      defaultValue: "15a_125v",
    },
  ],
  91: [
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 100,
      defaultValue: 20,
    },
    {
      key: "box_type",
      label: "Box Type",
      valueType: "enum",
      required: true,
      enumOptions: ["new_work", "old_work"],
      defaultValue: "new_work",
    },
    {
      key: "gang_count",
      label: "Gang Count",
      valueType: "integer",
      required: false,
      minValue: 1,
      maxValue: 4,
      defaultValue: 1,
    },
    {
      key: "switch_type",
      label: "Switch Type",
      valueType: "enum",
      required: false,
      enumOptions: ["standard", "3way", "4way", "dimmer"],
      defaultValue: "standard",
    },
    {
      key: "device_grade",
      label: "Device Grade",
      valueType: "enum",
      required: false,
      enumOptions: ["standard", "commercial", "hospital"],
      defaultValue: "standard",
    },
  ],
  92: [
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 150,
      defaultValue: 25,
    },
    {
      key: "box_type",
      label: "Box Type",
      valueType: "enum",
      required: true,
      enumOptions: ["new_work", "old_work"],
      defaultValue: "new_work",
    },
    {
      key: "fixture_type",
      label: "Fixture Type",
      valueType: "enum",
      required: true,
      enumOptions: ["recessed", "surface", "pendant"],
      defaultValue: "recessed",
    },
    {
      key: "mounting_height",
      label: "Mounting Height",
      valueType: "enum",
      required: false,
      enumOptions: ["standard", "cathedral", "vaulted"],
      defaultValue: "standard",
    },
    {
      key: "ceiling_type",
      label: "Ceiling Type",
      valueType: "enum",
      required: false,
      enumOptions: ["drywall", "plaster", "drop_ceiling"],
      defaultValue: "drywall",
    },
  ],
  93: [
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 100,
      defaultValue: 20,
    },
    {
      key: "point_type",
      label: "Point Type",
      valueType: "enum",
      required: true,
      enumOptions: ["receptacle", "switch", "light"],
      defaultValue: "receptacle",
      helpText: "Select the type of rough-in point (receptacle, switch, or ceiling light)",
    },
  ],
  94: [
    {
      key: "point_type",
      label: "Point Type",
      valueType: "enum",
      required: true,
      enumOptions: ["receptacle", "switch", "light"],
      defaultValue: "receptacle",
      helpText: "Select the type of trim-out point (receptacle, switch, or ceiling light)",
    },
  ],
  95: [
    {
      key: "room_label",
      label: "Room Label / ID",
      valueType: "string",
      required: false,
      defaultValue: "Bedroom 1",
    },
    {
      key: "receptacle_qty",
      label: "Receptacle Outlets",
      valueType: "integer",
      required: true,
      minValue: 2,
      maxValue: 12,
      defaultValue: 4,
      helpText: "NEC 210.52(A): Spacing per 12 ft of wall",
    },
    {
      key: "switch_qty",
      label: "Light Switches",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 6,
      defaultValue: 2,
    },
    {
      key: "light_qty",
      label: "Ceiling Lights",
      valueType: "integer",
      required: true,
      minValue: 0,
      maxValue: 4,
      defaultValue: 1,
      helpText: "NEC 210.70(A)(1) requires at least 1 switched lighting outlet",
    },
    {
      key: "smoke_co_qty",
      label: "Smoke/CO Detectors",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 4,
      defaultValue: 1,
      helpText: "NEC 210.12(A): AFCI protection",
    },
    {
      key: "closet_light_qty",
      label: "Closet Lights",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 2,
      defaultValue: 0,
      helpText: "Add for walk-in closets",
    },
    {
      key: "ceiling_fan_qty",
      label: "Ceiling Fans",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 2,
      defaultValue: 0,
      helpText: "Add if customer wants ceiling fan prep",
    },
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 100,
      defaultValue: 30,
      helpText: "Estimated cable run length for all devices in room",
    },
  ],
  96: [
    {
      key: "room_label",
      label: "Room Label / ID",
      valueType: "string",
      required: false,
      defaultValue: "Bathroom 1",
    },
    {
      key: "bathroom_type",
      label: "Bathroom Type",
      valueType: "enum",
      required: true,
      enumOptions: ["powder_room", "half_bath", "full_bath", "master_bath"],
      defaultValue: "full_bath",
    },
    {
      key: "gfci_receptacle_qty",
      label: "GFCI Receptacle Outlets",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 8,
      defaultValue: 3,
      helpText: "NEC 210.52(D): At least one per sink, 36 in from sink edge; GFCI per 210.8(A)(1)",
    },
    {
      key: "switch_qty",
      label: "Light Switches",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 4,
      defaultValue: 2,
      helpText: "Typically light + fan/vent; adjust for layout",
    },
    {
      key: "light_qty",
      label: "Light Fixtures",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 6,
      defaultValue: 2,
      helpText: "Vanity, ceiling, etc. per NEC 210.70",
    },
    {
      key: "exhaust_fan_qty",
      label: "Exhaust Fan",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 1,
      defaultValue: 1,
      helpText: "Code-required by IRC for bathrooms without operable window",
    },
    {
      key: "dedicated_20a_circuit_qty",
      label: "Dedicated 20A Circuit",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 2,
      defaultValue: 1,
      helpText: "NEC 210.11(C)(3); may be shared between adjacent bathrooms",
    },
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 100,
      defaultValue: 25,
    },
  ],
  97: [
    {
      key: "room_label",
      label: "Room Label / ID",
      valueType: "string",
      required: false,
      defaultValue: "Kitchen",
    },
    {
      key: "configuration_type",
      label: "Kitchen Configuration",
      valueType: "enum",
      required: true,
      enumOptions: ["single_wall", "galley", "l_shape", "u_shape", "island"],
      defaultValue: "l_shape",
    },
    {
      key: "small_appliance_circuit_count",
      label: "Small-Appliance Circuits",
      valueType: "integer",
      required: true,
      minValue: 2,
      maxValue: 4,
      defaultValue: 2,
      helpText: "NEC 210.11(C)(1): minimum 2 required",
    },
    {
      key: "countertop_gfci_qty",
      label: "Countertop GFCI Receptacles",
      valueType: "integer",
      required: true,
      minValue: 2,
      maxValue: 8,
      defaultValue: 4,
      helpText: "NEC 210.52(C): max 12 in. spacing; adjust for island/peninsula",
    },
    {
      key: "switch_qty",
      label: "Light Switches",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 6,
      defaultValue: 2,
      helpText: "Typical: overhead + under-cabinet; adjust for layout",
    },
    {
      key: "light_qty",
      label: "Ceiling Light Fixtures",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 6,
      defaultValue: 2,
      helpText: "Overhead + under-cabinet or recessed; adjust for design",
    },
    {
      key: "recessed_light_qty",
      label: "Recessed Lights",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 12,
      defaultValue: 0,
      helpText: "Optional — add per design",
    },
    {
      key: "dishwasher_disposal_qty",
      label: "Dishwasher / Disposal Circuit",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 1,
      defaultValue: 1,
      helpText: "Common paired appliance scope",
    },
    {
      key: "microwave_hood_qty",
      label: "Microwave / Hood Circuit",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 1,
      defaultValue: 1,
      helpText: "If microwave is hardwired or on dedicated circuit",
    },
    {
      key: "range_circuit_qty",
      label: "Range Circuit",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 1,
      defaultValue: 0,
      helpText: "Add if electric range; not included by default (may be gas)",
    },
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 150,
      defaultValue: 40,
      helpText: "Kitchens have longer runs due to multiple circuits",
    },
  ],
  98: [
    {
      key: "room_label",
      label: "Room Label / ID",
      valueType: "string",
      required: false,
      defaultValue: "Laundry Room",
    },
    {
      key: "laundry_circuit_qty",
      label: "Laundry Circuit (20A)",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 2,
      defaultValue: 1,
      helpText: "NEC 210.11(C)(2) dedicated circuit required",
    },
    {
      key: "receptacle_qty",
      label: "Receptacle Outlets",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 4,
      defaultValue: 2,
      helpText: "NEC 210.52(F): At least one per washer and dryer",
    },
    {
      key: "switch_qty",
      label: "Light Switches",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 2,
      defaultValue: 1,
      helpText: "For overhead light",
    },
    {
      key: "light_qty",
      label: "Ceiling Light Fixtures",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 2,
      defaultValue: 1,
    },
    {
      key: "dryer_circuit_qty",
      label: "Dryer Circuit",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 1,
      defaultValue: 1,
      helpText: "Set to 0 if gas dryer",
    },
    {
      key: "water_heater_circuit_qty",
      label: "Water Heater Circuit",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 1,
      defaultValue: 0,
      helpText: "Add if electric water heater in laundry area",
    },
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 100,
      defaultValue: 25,
    },
  ],
  99: [
    {
      key: "room_label",
      label: "Room Label / ID",
      valueType: "string",
      required: false,
      defaultValue: "Garage",
    },
    {
      key: "garage_size",
      label: "Garage Size",
      valueType: "enum",
      required: true,
      enumOptions: ["single_car", "two_car", "three_car", "detached", "carport"],
      defaultValue: "two_car",
    },
    {
      key: "gfci_receptacle_qty",
      label: "GFCI Receptacle Outlets",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 6,
      defaultValue: 2,
      helpText: "NEC 210.52(G): At least one per wall; GFCI per 210.8(A)(2)",
    },
    {
      key: "switch_qty",
      label: "Light Switches",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 3,
      defaultValue: 1,
      helpText: "For overhead lights",
    },
    {
      key: "light_qty",
      label: "Ceiling Light Fixtures",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 6,
      defaultValue: 2,
      helpText: "NEC 210.70(A)(2)(a) requires lighting; adjust for size",
    },
    {
      key: "exterior_receptacle_qty",
      label: "Exterior Receptacles",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 2,
      defaultValue: 0,
      helpText: "If front-of-garage exterior receptacle desired",
    },
    {
      key: "garage_door_opener_qty",
      label: "Garage Door Opener Circuit",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 2,
      defaultValue: 1,
      helpText: "Typical dedicated circuit for opener",
    },
    {
      key: "shop_equipment_circuit_qty",
      label: "Shop Equipment Circuits",
      valueType: "integer",
      required: false,
      minValue: 0,
      maxValue: 4,
      defaultValue: 0,
      helpText: "Add per customer scope",
    },
    {
      key: "branch_circuit_cable_length",
      label: "Branch Circuit Cable Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 10,
      maxValue: 100,
      defaultValue: 35,
      helpText: "Adjust for garage size and panel distance",
    },
  ],
  100: [
    {
      key: "current_service_size",
      label: "Current Service Size",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 200,
      defaultValue: 100,
    },
    {
      key: "new_service_size",
      label: "New Service Size",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 100,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "service_height",
      label: "Service Entry Height",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 8,
      maxValue: 40,
      defaultValue: 10,
    },
  ],
  101: [
    {
      key: "source_circuit_mode",
      label: "Source Circuit",
      valueType: "enum",
      required: true,
      enumOptions: ["new_breaker", "existing_circuit_extension"],
      defaultValue: "new_breaker",
      helpText: "Existing circuit extension auto-sets breaker quantity to zero.",
    },
    {
      key: "circuit_length",
      label: "Circuit Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 150,
      defaultValue: 30,
    },
    {
      key: "amp_rating",
      label: "Circuit Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 15,
      maxValue: 50,
      defaultValue: 20,
    },
    {
      key: "location_type",
      label: "Location Type",
      valueType: "enum",
      required: true,
      enumOptions: ["interior", "exterior", "damp"],
      defaultValue: "interior",
    },
    {
      key: "raceway_type",
      label: "Raceway / Cable Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nm", "emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ser", "ac_mc"],
      defaultValue: "nm",
    },
    {
      key: "breaker_qty",
      label: "Breaker Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 1,
      estimatorFacing: false,
    },
  ],
  102: [
    {
      key: "source_circuit_mode",
      label: "Source Circuit",
      valueType: "enum",
      required: true,
      enumOptions: ["new_breaker", "existing_circuit_extension"],
      defaultValue: "new_breaker",
      helpText: "Existing circuit extension auto-sets breaker quantity to zero.",
    },
    {
      key: "circuit_length",
      label: "Circuit Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 150,
      defaultValue: 30,
    },
    {
      key: "fixture_count",
      label: "Number of Fixtures",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 20,
      defaultValue: 3,
    },
    {
      key: "light_type",
      label: "Light Type",
      valueType: "enum",
      required: true,
      enumOptions: ["standard", "recessed", "track", "under_cabinet"],
      defaultValue: "standard",
    },
    {
      key: "raceway_type",
      label: "Raceway / Cable Type",
      valueType: "enum",
      required: true,
      enumOptions: ["nm", "emt", "pvc", "fmc", "lfmc", "imc", "rigid", "ser", "ac_mc"],
      defaultValue: "nm",
    },
    {
      key: "breaker_qty",
      label: "Breaker Quantity",
      valueType: "integer",
      required: false,
      defaultValue: 1,
      estimatorFacing: false,
    },
  ],
  103: [
    {
      key: "existing_panel_amps",
      label: "Existing Panel Capacity",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "load_type",
      label: "Load Type",
      valueType: "enum",
      required: true,
      enumOptions: ["residential", "mixed_use", "commercial_light"],
      defaultValue: "residential",
    },
  ],
  104: [
    {
      key: "gang_count",
      label: "Gang Count",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 4,
      defaultValue: 1,
      helpText: "Number of dimmer switches to install in the new box (1–4).",
    },
    {
      key: "cable_length",
      label: "Cable Length",
      valueType: "number",
      required: true,
      unit: "lf",
      minValue: 1,
      maxValue: 100,
      helpText: "Total feet of 12/2 NM-B cable from breakers to switch box and back.",
    },
  ],
  105: [
    {
      key: "end_state",
      label: "End State",
      valueType: "enum",
      required: true,
      enumOptions: ["blank_plate", "constant_power_outlet"],
      defaultValue: "blank_plate",
      helpText: "blank_plate: switch removed and box blanked off. constant_power_outlet: switch leg rewired as always-on outlet.",
    },
  ],
  8: [
    {
      key: "plate_style",
      label: "Plate Style",
      valueType: "enum",
      required: true,
      enumOptions: ["standard", "oversized", "weather_resistant"],
      defaultValue: "standard",
    },
  ],
  15: [
    {
      key: "run_length",
      label: "Cable Run Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 100,
      defaultValue: 20,
    },
    {
      key: "attic_access",
      label: "Attic Access",
      valueType: "enum",
      required: true,
      enumOptions: ["accessible", "limited", "none"],
      defaultValue: "accessible",
    },
  ],
  25: [
    {
      key: "panel_amp_rating",
      label: "Panel Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 400,
      defaultValue: 200,
    },
    {
      key: "branch_circuit_count",
      label: "Number of Circuits to Rework",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 42,
      defaultValue: 6,
    },
  ],
  26: [
    {
      key: "panel_amp_rating",
      label: "Subpanel Amp Rating",
      valueType: "integer",
      required: true,
      unit: "A",
      minValue: 60,
      maxValue: 200,
      defaultValue: 100,
    },
    {
      key: "panel_location_type",
      label: "Panel Location",
      valueType: "enum",
      required: true,
      enumOptions: ["garage", "basement", "exterior", "interior_closet"],
      defaultValue: "garage",
    },
    {
      key: "grounding_upgrade_required",
      label: "Grounding Upgrade Required",
      valueType: "enum",
      required: true,
      enumOptions: ["yes", "no"],
      defaultValue: "no",
    },
  ],
  31: [
    {
      key: "mast_height",
      label: "Service Mast Height",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 8,
      maxValue: 40,
      defaultValue: 12,
    },
    {
      key: "service_overhead",
      label: "Service Type",
      valueType: "enum",
      required: true,
      enumOptions: ["overhead", "underground"],
      defaultValue: "overhead",
    },
  ],
  34: [
    {
      key: "rod_qty",
      label: "Number of Ground Rods",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 4,
      defaultValue: 1,
    },
    {
      key: "electrode_type",
      label: "Electrode Type",
      valueType: "enum",
      required: true,
      enumOptions: ["rod", "plate", "concrete_encased"],
      defaultValue: "rod",
    },
  ],
  66: [
    {
      key: "device_type_removed",
      label: "Device or Fixture Type",
      valueType: "enum",
      required: true,
      enumOptions: ["receptacle", "switch", "light_fixture", "other"],
      defaultValue: "receptacle",
    },
  ],
  67: [
    {
      key: "run_length",
      label: "Circuit Segment Length",
      valueType: "number",
      required: true,
      unit: "ft",
      minValue: 5,
      maxValue: 200,
      defaultValue: 30,
    },
    {
      key: "accessibility",
      label: "Accessibility",
      valueType: "enum",
      required: true,
      enumOptions: ["accessible", "difficult", "enclosed"],
      defaultValue: "accessible",
    },
  ],
  68: [
    {
      key: "panel_location_type",
      label: "Panel Location Type",
      valueType: "enum",
      required: true,
      enumOptions: ["interior", "exterior", "detached"],
      defaultValue: "interior",
    },
    {
      key: "hazard_present",
      label: "Hazard or Asbestos Present",
      valueType: "enum",
      required: true,
      enumOptions: ["yes", "no"],
      defaultValue: "no",
    },
  ],
  69: [
    {
      key: "splice_type",
      label: "Splice or Termination Type",
      valueType: "enum",
      required: true,
      enumOptions: ["wire_splice", "terminal_lug", "split_bolt"],
      defaultValue: "wire_splice",
    },
    {
      key: "access_difficulty",
      label: "Access Difficulty",
      valueType: "enum",
      required: true,
      enumOptions: ["easy", "moderate", "difficult"],
      defaultValue: "moderate",
    },
  ],
  70: [
    {
      key: "branch_circuit_count",
      label: "Number of Circuits to Rework",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 42,
      defaultValue: 4,
    },
  ],
  73: [
    {
      key: "patch_count",
      label: "Number of Patches",
      valueType: "integer",
      required: true,
      minValue: 1,
      maxValue: 20,
      defaultValue: 2,
    },
    {
      key: "surface_type",
      label: "Surface Type",
      valueType: "enum",
      required: true,
      enumOptions: ["drywall", "plaster", "finished_wall"],
      defaultValue: "drywall",
    },
  ],
  74: [
    {
      key: "box_type",
      label: "Box Type",
      valueType: "enum",
      required: true,
      enumOptions: ["round", "square", "rectangular"],
      defaultValue: "square",
    },
    {
      key: "installation_type",
      label: "Installation Type",
      valueType: "enum",
      required: true,
      enumOptions: ["surface_mount", "flush_mount", "in_framing"],
      defaultValue: "surface_mount",
    },
  ],
};

export const PHASE_1_VARIANTS: Record<number, AssemblyVariantSeed[]> = {
  6: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "route_context", variantValue: "finished_wall" },
    { variantKey: "route_context", variantValue: "attic_accessible" },
  ],
  7: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "route_context", variantValue: "finished_wall" },
  ],
  13: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "route_context", variantValue: "attic_accessible" },
  ],
  14: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "route_context", variantValue: "attic_accessible" },
  ],
  16: [
    { variantKey: "location_context", variantValue: "exterior_weather_resistant" },
  ],
  17: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "route_context", variantValue: "finished_wall" },
    { variantKey: "route_context", variantValue: "attic_accessible" },
  ],
  18: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
  ],
  19: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "wiring_method", variantValue: "nm_cable" },
    { variantKey: "wiring_method", variantValue: "conduit" },
  ],
  20: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "feeder_method", variantValue: "ser_overhead" },
    { variantKey: "feeder_method", variantValue: "thhn_conduit" },
  ],
  21: [
    { variantKey: "route_context", variantValue: "underground" },
    { variantKey: "route_context", variantValue: "overhead_aerial" },
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
  ],
  27: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "service_context", variantValue: "overhead" },
    { variantKey: "service_context", variantValue: "underground" },
  ],
  28: [
    { variantKey: "service_context", variantValue: "overhead" },
    { variantKey: "service_context", variantValue: "underground" },
  ],
  29: [
    { variantKey: "service_context", variantValue: "overhead" },
    { variantKey: "service_context", variantValue: "underground" },
  ],
  30: [
    { variantKey: "location_context", variantValue: "exterior_weather_resistant" },
  ],
  32: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "service_context", variantValue: "full_upgrade_package" },
  ],
  75: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
  ],
  77: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "maintenance" },
  ],
  78: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "route_context", variantValue: "attic_accessible" },
  ],
  79: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "maintenance" },
  ],
  80: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "route_context", variantValue: "attic_accessible" },
  ],
  83: [
    { variantKey: "route_context", variantValue: "underground" },
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
  ],
  89: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "detached_structure", variantValue: "true" },
  ],
  38: [
    { variantKey: "garage_type", variantValue: "detached_garage" },
    { variantKey: "garage_type", variantValue: "detached_shop" },
    { variantKey: "route_context", variantValue: "overhead" },
    { variantKey: "route_context", variantValue: "underground" },
  ],
  40: [
    { variantKey: "route_context", variantValue: "overhead" },
    { variantKey: "route_context", variantValue: "underground" },
  ],
  41: [
    { variantKey: "route_context", variantValue: "overhead" },
    { variantKey: "route_context", variantValue: "underground" },
  ],
  42: [
    { variantKey: "device_mounting", variantValue: "post" },
    { variantKey: "device_mounting", variantValue: "wall" },
    { variantKey: "route_context", variantValue: "overhead" },
  ],
  84: [
    { variantKey: "chime_location", variantValue: "existing" },
    { variantKey: "chime_location", variantValue: "new_location" },
  ],
  90: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "device_type", variantValue: "standard_receptacle" },
  ],
  91: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "device_type", variantValue: "standard_switch" },
  ],
  92: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "fixture_type", variantValue: "recessed_light" },
  ],
  93: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "point_type", variantValue: "receptacle" },
    { variantKey: "point_type", variantValue: "switch" },
    { variantKey: "point_type", variantValue: "light" },
  ],
  94: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "point_type", variantValue: "receptacle" },
    { variantKey: "point_type", variantValue: "switch" },
    { variantKey: "point_type", variantValue: "light" },
  ],
  95: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "room_type", variantValue: "bedroom" },
  ],
  96: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "room_type", variantValue: "bathroom" },
  ],
  97: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "room_type", variantValue: "kitchen" },
  ],
  98: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "room_type", variantValue: "laundry" },
  ],
  99: [
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "room_type", variantValue: "garage" },
  ],
  100: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
  ],
  101: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "location_type", variantValue: "interior" },
    { variantKey: "location_type", variantValue: "exterior" },
  ],
  102: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "light_type", variantValue: "standard" },
    { variantKey: "light_type", variantValue: "recessed" },
  ],
  103: [
    { variantKey: "load_type", variantValue: "residential" },
    { variantKey: "load_type", variantValue: "mixed_use" },
  ],
  104: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "service_call" },
    { variantKey: "gang_count", variantValue: "1" },
    { variantKey: "gang_count", variantValue: "2" },
    { variantKey: "gang_count", variantValue: "4" },
  ],
  105: [
    { variantKey: "end_state", variantValue: "blank_plate" },
    { variantKey: "end_state", variantValue: "constant_power_outlet" },
  ],
  8: [
    { variantKey: "plate_style", variantValue: "standard" },
    { variantKey: "plate_style", variantValue: "weather_resistant" },
  ],
  15: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "new_construction" },
    { variantKey: "attic_access", variantValue: "accessible" },
  ],
  25: [
    { variantKey: "project_mode", variantValue: "remodel" },
    { variantKey: "project_mode", variantValue: "service_diagnostic" },
  ],
  26: [
    { variantKey: "grounding_upgrade_required", variantValue: "yes" },
    { variantKey: "grounding_upgrade_required", variantValue: "no" },
  ],
  31: [
    { variantKey: "service_overhead", variantValue: "overhead" },
  ],
  34: [
    { variantKey: "electrode_type", variantValue: "rod" },
    { variantKey: "electrode_type", variantValue: "plate" },
  ],
  66: [
    { variantKey: "device_type_removed", variantValue: "receptacle" },
    { variantKey: "device_type_removed", variantValue: "switch" },
    { variantKey: "device_type_removed", variantValue: "light_fixture" },
  ],
  67: [
    { variantKey: "accessibility", variantValue: "accessible" },
    { variantKey: "accessibility", variantValue: "difficult" },
  ],
  68: [
    { variantKey: "panel_location_type", variantValue: "interior" },
    { variantKey: "panel_location_type", variantValue: "exterior" },
  ],
  69: [
    { variantKey: "splice_type", variantValue: "wire_splice" },
    { variantKey: "splice_type", variantValue: "terminal_lug" },
  ],
  70: [
    { variantKey: "project_mode", variantValue: "service_diagnostic" },
    { variantKey: "project_mode", variantValue: "remodel" },
  ],
  73: [
    { variantKey: "surface_type", variantValue: "drywall" },
    { variantKey: "surface_type", variantValue: "plaster" },
  ],
  74: [
    { variantKey: "installation_type", variantValue: "surface_mount" },
    { variantKey: "installation_type", variantValue: "flush_mount" },
  ],
};
